### ISSUE TITLE
What's the meaning of the abbreviation NMP in the picture?

### ISSUE THREAD

**Issue by ZhengMengbin** [toshi-k/kaggle-airbus-ship-detection-challenge#1]
Hi! Thank you very much for your open source.
But I want to know what's the meaning of the abbreviation NMP in the picture as bellow?
![image](https://user-images.githubusercontent.com/26650043/49087732-b9229b00-f292-11e8-8383-772dc28bc6bc.png)

**Comment by toshi-k** [comment]
NMP stands for Non-maximum suppression. It aggregates predicted boxes and reduces overlap. I implement it in this file.
https://github.com/toshi-k/kaggle-airbus-ship-detection-challenge/blob/master/source/02_oriented_ssd/lib/non_maximum_suppression.py
